# Generated by Django 4.2.27 on 2025-12-18 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.CharField(choices=[('banker', 'バンカー'), ('player', 'プレイヤー'), ('tie', '引き分け')], max_length=10, verbose_name='勝者')),
                ('consecutive_count', models.IntegerField(default=1, verbose_name='連勝回数')),
                ('tie_positions', models.JSONField(default=list, verbose_name='引き分けの位置')),
                ('column_position', models.IntegerField(verbose_name='列の位置')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baccara_roadmaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '罫線',
                'verbose_name_plural': '罫線',
                'ordering': ['column_position'],
            },
        ),
    ]
