# Generated by Django 6.0.1 on 2026-06-04 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baccara', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roadmap',
            options={'ordering': ['column_position']},
        ),
    ]
